### ISSUE TITLE
How to use spotify module?

### ISSUE THREAD

**Issue by sedbytes** [freak532486/nord-rice-dotfiles#1]
Hi, Thank you so much for your dotfiles! 
I saw your post on r/unixporn and fell in love with it immediately.

Everything is perfect other than the spotify module for polybar:

It doesn't seem to detect my spotify client for some reason. I tried `spotifyctl status` in my terminal and it's all ok.

I read the polybar docs about IPC modules and it sounds like I need an *external script* to perform `polybar-msg` commands accordingly. Like `polybar-msg hook spotify 2` to make it display the song name but it doesn't update as the song changes.

What do you do to make this work?

**Comment by freak532486** [comment]
Hi,

Yeah, I didn't think about that. I'm using [this](https://github.com/mihirlad55/polybar-spotify-module) module for spotify. Install it as stated in the readme (or, if you're using arch, it's in the AUR under `polybar-spotify-module` or something) and enable `spotify-listener` with `systemctl --user enable spotify-listener`. It should work then.

I got some segfaults by the `spotify-listener`-module sometimes when restarting polybar, don't know why. Currently it's stable for me though.

**Comment by sedbytes** [comment]
Thank you so much, It worked!

Fortunately, I didn't get any segfaults yet.
